project:
  type: website

website:
  title: "A Bit Correlated"
  site-url: https://tpolakovic.github.io
  description: "Physics and stuff..."
  favicon: favicon.ico
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/tpolakovic/tpolakovic.github.io

format:
  html:
    theme: united
    css: styles.css



