project:
  type: website

website:
  title: "A Bit Correlated"
  site-url: https://tpolakovic.github.io
  description: "Physics and stuff..."
  favicon: favicon.ico
  open-graph: true
  page-footer: "© Copyright 2022, Tomas Polakovic. Except where otherwise noted, all text and images
  licensed CC-BY-NC 4.0."
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/tpolakovic/tpolakovic.github.io

format:
  html:
    theme: united
    css: styles.css

execute:
  cache: true
